/*
 *    Class definition of the SoC Designer component <IDCT>
 *
 *    This code has been generated by the SoC Designer Component Wizard.
 *    Copyright (c) 2004-2005 by ARM Limited, 2000-2004 by AXYS Design Automation Inc., Irvine, CA, USA and AXYS GmbH, Herzongenrath
 *
 */

#ifndef IDCT__H
#define IDCT__H

#include "maxsim.h"
#include "AHB_Transaction.h"


#include "MxSaveRestore.h"


// Place global class declarations here:


class IDCT_MxDI;




class IDCT : public sc_mx_module
    , public MxSaveRestore
{
    // Declare your friends here:

    friend class ahb_s_TS;

    friend class IDCT_MxDI;

public:
    // Place instance declarations for the Ports here:
    ahb_s_TS* ahb_s_TSlave;
	
    // constructor / destructor
    IDCT(sc_mx_m_base* c, const string &s);
    virtual ~IDCT();

    // overloaded methods for clocked components
    void communicate();
    void update();

    // Implementation of MxSaveRestore interface methods
    virtual bool saveData( MxODataStream &data );
    virtual bool restoreData( MxIDataStream &data );


    // overloaded sc_mx_module methods
    string getName();
    void setParameter(const string &name, const string &value);
    string getProperty( MxPropertyType property );
    void init();
    void terminate();
    void reset(MxResetLevel level, const MxFileMapIF *filelist);
    // The MxDI interface.
    MXDI* getMxDI();

    //Initialize the Port Properties
    void initSignalPort(sc_mx_signal_p_base* signalIf);
    void initTransactionPort(sc_mx_transaction_p_base* transIf);


private:
    bool initComplete; 
    bool p_enableDbgMsg;

    // User defined parameters:
    MxU64 p_ahb_s_addrSize;
    MxU64 p_ahb_s_baseAddress;
	TAHBSignals *pSignals;	//  pointer to the shared signal structure of the bus


    // Declare MXDI Interface
    MXDI* mxdi;

    MxU32 r_reg0;
    MxU32 r_reg1;
    MxU32 r_reg2;
    MxU32 r_reg3;
    MxU32 r_reg4;
    MxU32 r_reg5;
    MxU32 r_reg6;
    MxU32 r_reg7;
    MxU32 r_r_status;
    MxU32 r_r_ctrl;



    // place your private functions and data members here:
    // ...
    // This shows an example state variable for the save/restore mechanism.
    // int		exampleStateVariable;

};

#endif
